"""compute distance matrices for all rats - grid cells.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1RBHYcCl7PpMa_AxSlh1CZRAT6wOy-2
"""



""" 
##Aanalyze all rats, all modules and all days (27 total)

The datasets analyzed in this paper included recordings from three rats, labeled Q, R, and S. Grid cell activity from these rats was recorded across several distinct experimental conditions, including:

1. Open-field foraging on day 1 (OF day 1)
2. Open-field foraging on day 2 (OF day 2)
3. Wagon-wheel track foraging (WW)
4. Slow-wave sleep (SWS)
5. Rapid eye-movement sleep (REM)

The recordings were organized into different grid modules (Q1, Q2, R1, R2, R3, and S1). In total, the study analyzed 27 unique combinations of these grid modules with the various experimental conditions listed above.

For rat 'S', specifically, two wagon-wheel (WW) task sessions were concatenated to increase the sample size for analysis.

Thus, the complete list of datasets includes:

- Rat Q: Modules Q1 and Q2, recorded under OF day 1, OF day 2, WW, REM, and SWS conditions.
- Rat R: Modules R1, R2, and R3, recorded under OF day 1, OF day 2, WW, REM, and SWS conditions (note that recordings from Rat R spanned two recording days with similar anatomical distributions of recorded cells across both sessions).
- Rat S: Module S1, recorded under OF day 1, OF day 2, WW (with two concatenated sessions), REM, and SWS conditions.

"""# With PCA"""

from grid_cells_utils import *

metric = 'cosine'
maxdim = 2
coeff = 2
active_times = 15000
k = 1000
num_times = 5
n_points = 1200
nbs = 800
dim = 6

folder = '/Toroidal_topology_grid_cell_data/'
#f = np.load(folder + 'rat_s_grid_modules_1.npz', allow_pickle = True)
#print(f)
# for rat_name, mod_name, sess_name, day_name in (('R', '1', 'OF', 'day1'),
#                                                 ('R', '2', 'OF', 'day1'),
#                                                 ('R', '3', 'OF', 'day1'),
#                                                 ('R', '1', 'WW', 'day1'),
#                                                 ('R', '2', 'WW', 'day1'),
#                                                 ('R', '3', 'WW', 'day1'),
#                                                 ('R', '1', 'OF', 'day2'),
#                                                 ('R', '2', 'OF', 'day2'),
#                                                 ('R', '3', 'OF', 'day2'),
#                                                 ('R', '1', 'REM', 'day2'),
#                                                 ('R', '2', 'REM', 'day2'),
#                                                 ('R', '3', 'REM', 'day2'),
#                                                 ('R', '1', 'SWS', 'day2'),
#                                                 ('R', '2', 'SWS', 'day2'),
#                                                 ('R', '3', 'SWS', 'day2'),
#                                                 ('Q', '1', 'OF', ''),
#                                                 ('Q', '2', 'OF', ''),
#                                                 ('Q', '1', 'WW', ''),
#                                                 ('Q', '2', 'WW', ''),
#                                                 ('Q', '1', 'REM', ''),
#                                                 ('Q', '2', 'REM', ''),
#                                                 ('Q', '1', 'SWS', ''),
#                                                 ('Q', '2', 'SWS', ''),
#                                                 ('S', '1', 'OF', ''),
#                                                 ('S', '1', 'WW', ''),
#                                                 ('S', '1', 'REM', ''),
#                                                 ('S', '1', 'SWS', '')
#                                                 ):
for rat_name, mod_name, sess_name, day_name in (('S', '1', 'OF', ''),
                                                ('S', '1', 'WW', ''),
                                                ('S', '1', 'REM', ''),
                                                ('S', '1', 'SWS', '')
                                                ):
    if sess_name in ('OF', 'WW'):
        sspikes,__,__,__,__ = get_spikes(rat_name, mod_name, day_name, sess_name, bType = 'pure',
                                         bSmooth = True, bSpeed = True, folder = folder)
    else:
        sspikes = get_spikes(rat_name, mod_name, day_name, sess_name, bType = 'pure', bSmooth = True, bSpeed = False, folder = folder)

    num_neurons = len(sspikes[0,:])

    times_cube = np.arange(0,len(sspikes[:,0]),num_times)
    movetimes = np.sort(np.argsort(np.sum(sspikes[times_cube,:],1))[-active_times:])
    movetimes = times_cube[movetimes]

    dim_red_spikes_move_scaled,__,__ = pca(preprocessing.scale(sspikes[movetimes,:]), dim = dim)
    indstemp,dd,fs  = sample_denoising(dim_red_spikes_move_scaled,  k,
                                        n_points, 1, metric)
    dim_red_spikes_move_scaled = dim_red_spikes_move_scaled[indstemp,:]
    X = squareform(pdist(dim_red_spikes_move_scaled, metric))
    knn_indices = np.argsort(X)[:, :nbs]
    knn_dists = X[np.arange(X.shape[0])[:, None], knn_indices].copy()
    sigmas, rhos = smooth_knn_dist(knn_dists, nbs, local_connectivity=0)
    rows, cols, vals = compute_membership_strengths(knn_indices, knn_dists, sigmas, rhos)
    result = coo_matrix((vals, (rows, cols)), shape=(X.shape[0], X.shape[0]))
    result.eliminate_zeros()
    transpose = result.transpose()
    prod_matrix = result.multiply(transpose)
    result = (result + transpose - prod_matrix)
    result.eliminate_zeros()
    d = result.toarray()
    d = -np.log(d)
    np.fill_diagonal(d,0)

    np.savez(f'/n/home03/eivshina/grid_cell_analysis/ds_pca/d_{rat_name}_{day_name}_{sess_name}_mod_{mod_name}', ds_all = d)