"""cup_length_analysis_of_grid_cells.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183-GwLeDnVQ5DdbMQ20NwqXwvexR_58_
"""

"""# Run cup length analysis on all available grid modules (in ds and ds_pca folders)"""
import os
import sys
import glob
from cup_length_utils import *
from dreimac_utils import *
from dreimac_combinatorial import *
import pickle


# Parameters
n_landmarks = 250
print('# of landmarks: ', n_landmarks)
# min_persistence is set to choose the top 2 most persistent 1-bars

path2persistence_diagrams = f'/results/persistent_diagrams/with_pca/quick/{n_landmarks}_land/'
path2persistence_diagrams_pkl = f'/results/persistent_diagrams/with_pca/quick/{n_landmarks}_land/dgms/'
path2cup_length_barcodes = f'/results/cup_length_barcodes/with_pca/quick/{n_landmarks}_land/'

os.makedirs(path2persistence_diagrams, exist_ok=True)
os.makedirs(path2persistence_diagrams_pkl, exist_ok=True)
os.makedirs(path2cup_length_barcodes, exist_ok=True)

folder = "/ds_pca"


# Build a file pattern to match all .npz files in the folder
file_pattern = os.path.join(folder, "*.npz")
# Use glob to get a list of file paths
files = glob.glob(file_pattern)

# module name convention: {rat_name}_{day_name}_{sess_name}_mod_{mod_name}'


for f in files:
    try:
        d = np.load(f, allow_pickle=True)['ds_all'][()]
        print('Loaded ', f)

        threshold = np.max(d[~np.isinf(d)])
        # Step 1: compute persistent homology on a subsampled point cloud.
        ripser_result = rips_filtration_diagram(data = d, distance_matrix = True, n_landmarks = n_landmarks, thresh = threshold)
        dgms = ripser_result['dgms']
        
        fig, ax = plt.subplots()
        plot_diagrams(dgms, show=False)
        module_name = os.path.splitext(os.path.basename(f))[0]
        dgm_filename = os.path.join(path2persistence_diagrams_pkl, module_name + '_dgms.pkl')
        with open(dgm_filename, 'wb') as f:
            pickle.dump(dgms, f)
        
        ph_path = os.path.join(path2persistence_diagrams, module_name + '_ph.png')
        fig.savefig(ph_path)
        plt.close()


        # compute the threshold persistence for which we compute cup product
        min_persistence = compute_threshold_persistence(dgms[1])

        t0 = time.time()
        # Step 2: compute persistent cup length
        (persistent_cup_length_matrix, b_times, d_times, cup_lengths_2) = compute_persistent_cup_length_ripser(2, \
                                                            ripser_result, \
                                                            d, \
                                                            min_persistence, \
                                                            threshold)

        t1 = time.time(); elapsed_time = (t1 - t0) / 60  # Convert seconds to minutes
        print(f"Function took {elapsed_time:.2f} minutes to run.")

        output_file = os.path.join(path2cup_length_barcodes, f"{module_name}_cup_length_intervals.txt")

        if cup_lengths_2:
            with open(output_file, 'w') as f:
                for birth, death in cup_lengths_2:
                    f.write(f"{birth}\t{death}\n")
            print(f"Saved cup length intervals to {output_file}")
        else:
            print("cup_lengths_2 is empty; nothing to save.")

    except Exception as e:
        print(f"Failed: {e}")